apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: persistence
message: This is an OpenShift template to deploy persistence.
metadata:
  name: persistence
  annotations:
    description: "persistence Template"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: persistence
  data:
    quarkus-log-level: 'INFO'
    quarkus-log-file-path: '/tmp/quarkus.log'
    google-key: 'replaceme'
    quarkus-http-auth-permission-authenticated-paths: '/*'
    quarkus-http-auth-permission-authenticated-policy: 'authenticated'
- apiVersion: v1
  kind: Secret
  metadata:
    name: persistence
  data:
    quarkus-mongodb-connection-string: bW9uZ29kYjovL2xvZ2luOnBhc3NAbW9uZ29kYjoyNzAxNy9tcnQ=
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: persistence
    labels:
      app: persistence
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: persistence
    template:
      metadata:
        labels:
          app: persistence
        annotations:
          kubernetes.io/change-cause: ${CAUSE}
          gitcommit: ${CAUSE}
      spec:
        containers:
          - name: persistence
            image: ${IMAGE}
            env:
              - name: QUARKUS_MONGODB_CONNECTION_STRING
                valueFrom:
                  secretKeyRef:
                    name: persistence
                    key: quarkus-mongodb-connection-string
              - name: QUARKUS_LOG_LEVEL
                valueFrom:
                  configMapKeyRef:
                    name: persistence
                    key: quarkus-log-level
              - name: QUARKUS_LOG_FILE_PATH
                valueFrom:
                  configMapKeyRef:
                    name: persistence
                    key: quarkus-log-file-path
              - name: GOOGLE_KEY
                valueFrom:
                  configMapKeyRef:
                    name: persistence
                    key: google-key
              - name: QUARKUS_HTTP_AUTH_PERMISSION_AUTHENTICATED_PATHS
                valueFrom:
                  configMapKeyRef:
                    name: persistence
                    key: quarkus-http-auth-permission-authenticated-paths
              - name: QUARKUS_HTTP_AUTH_PERMISSION_AUTHENTICATED_POLICY
                valueFrom:
                  configMapKeyRef:
                    name: persistence
                    key: quarkus-http-auth-permission-authenticated-policy
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
            imagePullPolicy: IfNotPresent
            livenessProbe:
              httpGet:
                path: /q/health/live
                port: 8080
            readinessProbe:
              httpGet:
                path: /q/health/ready
                port: 8080
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: persistence
    labels:
      app: persistence
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: persistence
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: persistence
    labels:
      app: persistence
  spec:
    to:
      kind: Service
      name: persistence
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
- description: Container image to use
  name: IMAGE
  required: true
- description: Description of this deployment
  name: CAUSE
  required: true