apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-artifacts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-varlibcontainers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: persistence-pipelineconfig
data:
  dev-image-path: 'image-registry.openshift-image-registry.svc:5000/mrt/persistence'
  dev-latest-built-image: ''
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: persistence-s2ienvironment
data:
  MAVEN_S2I_GOALS: "package"
  S2I_SOURCE_DEPLOYMENTS_FILTER: "*-runner.jar lib"
  MAVEN_ARGS_APPEND: "-Dquarkus.package.type=uber-jar"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: persistence-dev-pipeline
spec:
  params:
    - name: repo-url
  workspaces:
    - name: src
    - name: artifacts
    - name: varlibcontainers
    - name: empty
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: src
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: compile
      taskRef:
        name: s2i-build
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: src
        - name: artifacts
          workspace: artifacts
      params:
        - name: S2I_IMAGE
          value: "registry.access.redhat.com/ubi8/openjdk-11"
        - name: CONTEXT
          value: "persistence"
        - name: S2I_ENVIRONMENT
          value: "persistence-s2ienvironment"
        - name: INCREMENTAL
          value: "true"
    - name: get-dev-path
      taskRef:
        name: get-configmap-value
      runAfter:
        - compile
      params:
        - name: CONFIGMAP-NAME
          value: "persistence-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-image-path"
    - name: build
      taskRef:
        name: image-from-s2i
      runAfter:
        - get-dev-path
      params:
        - name: S2I_IMAGE
          value: "registry.access.redhat.com/ubi8/openjdk-11"
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(tasks.get-dev-path.results.VALUE)
        - name: CONTEXT
          value: "persistence"
      workspaces:
        - name: source
          workspace: src
        - name: varlibcontainers
          workspace: varlibcontainers
    - name: deploy
      taskRef:
        name: openshift-actions
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: src
      params:
        - name: CONTEXT
          value: "persistence"
        - name: SCRIPT
          value: |
            oc process -p IMAGE=$(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST) -p CAUSE=$(tasks.fetch-repository.results.commit) -f persistence-template.yaml | oc apply -f -
    - name: update-built-image
      taskRef:
        name: set-configmap-value
      runAfter:
        - deploy
      params:
        - name: CONFIGMAP-NAME
          value: "persistence-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image"
        - name: VALUE
          value: $(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST)
