apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: template-infra
message: This is a template to start infra components required for mrt project.
metadata:
  name: template-infra
  annotations:
    description: "infra template"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mongodb
  data:
    mongodb-database: 'mrt'
- apiVersion: v1
  kind: Secret
  metadata:
    name: mongodb
  data:
    mongodb-admin-password: YWRtaW5wYXNzd29yZA==
    mongodb-user: bG9naW4=
    mongodb-password: cGFzcw==
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mongodb
    labels:
      app: mongodb
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mongodb
    template:
      metadata:
        labels:
          app: mongodb
      spec:
        containers:
          - name: mongodb
            image: quay.io/gmagnotta/mongodb
            ports:
              - containerPort: 27017
                protocol: TCP
            env:
              - name: MONGODB_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongodb
                    key: mongodb-admin-password
              - name: MONGODB_USER
                valueFrom:
                  secretKeyRef:
                    name: mongodb
                    key: mongodb-user
              - name: MONGODB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongodb
                    key: mongodb-password
              - name: MONGODB_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: mongodb
                    key: mongodb-database
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: mongodb
    labels:
      app: mongodb
  spec:
    ports:
      - name: 27017-tcp
        protocol: TCP
        port: 27017
        targetPort: 27017
    selector:
      app: mongodb
    type: ClusterIP
    sessionAffinity: None