apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sample-kube-resources-subscription
  namespace: mrt-app
  annotations:
    apps.open-cluster-management.io/git-path: gitops/app
    apps.open-cluster-management.io/git-branch: main 
spec:
  channel: mrt-app/sample-kube-resources-git
  placement:
    placementRef:
      kind: PlacementRule
      name: placementrule-mrt-app